pipeline {
    agent any
    environment {
        DOCKER_HOST = 'tcp://dind:2375'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nitin-rajesh/CalcOps'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build --tag=docker-calicos:latest .'
            }
        }

    }
}
