pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-22-jammy'
            args '--network=jenkins-net'
        }
    }
    environment {
        DOCKER_HOST = 'tcp://dind:2375'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nitin-rajesh/CalcOps'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build --tag=docker-calicos:latest .'
            }
        }

    }
}
