pipeline {
    agent any

    stages {
        stage('Check prereqs') {
            steps {
                sh 'docker version'
                sh 'docker ps'
                sh 'mvn -v'
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'simple_code',
                    url: 'https://github.com/nitin-rajesh/CalcOps'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build --tag=docker-calicos:latest .'
            }
        }

    }
}
