pipeline {
    agent any
    environment {
        DOCKERHUB_USERNAME = 'nitinrajesh'
    }
    stages {
        stage('Check prereqs') {
            steps {
                sh 'docker version'
                sh 'docker ps'
                sh 'mvn -v'
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'simple_code',
                    url: 'https://github.com/nitin-rajesh/CalcOps'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn -f calicos/pom.xml clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build --tag=docker-calicos:latest calicos/.'
                sh 'docker images'
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker tag docker-calicos:latest ${DOCKERHUB_USERNAME}/docker-calicos:latest"
                    sh "docker push ${DOCKERHUB_USERNAME}/docker-calicos:latest"
                }
            }
        }
    }
}
